#ifndef NHV_VMCS_H
#define NHV_VMCS_H

#include <stdint.h>

/*
 * Intel VMCS field encoding (SDM Vol.3, "VMCS field encodings"):
 *
 *   encoding = (width << 14) | (high << 13) | (type << 10) | index
 *
 *   width: 0 = 16-bit, 1 = 64-bit, 2 = 32-bit, 3 = natural width
 *   high : 1 = high 32 bits of a 64-bit field (only with width == 2)
 *   type : 0 = control, 1 = read-only (VM-exit info), 2 = guest state, 3 = host state
 */

#define NHV_FIELD_ENCODE(width, high, type, index) \
    ((((uint32_t)(width)) << 14) | (((uint32_t)(high)) << 13) | \
     (((uint32_t)(type)) << 10) | ((uint32_t)(index)))

#define NHV_FIELD_WIDTH(enc)  (((enc) >> 14) & 3u)
#define NHV_FIELD_HIGH(enc)   (((enc) >> 13) & 1u)
#define NHV_FIELD_TYPE(enc)   (((enc) >> 10) & 3u)
#define NHV_FIELD_INDEX(enc)  ((enc) & 0x3FFu)

#define NHV_WIDTH_16     0u
#define NHV_WIDTH_64     1u
#define NHV_WIDTH_32     2u
#define NHV_WIDTH_NAT    3u

#define NHV_TYPE_CONTROL 0u
#define NHV_TYPE_RO      1u
#define NHV_TYPE_GUEST   2u
#define NHV_TYPE_HOST    3u

/* Field access classification. */
#define NHV_ACCESS_RW 0u
#define NHV_ACCESS_RO 1u

/*
 * A field descriptor: how wide a field is and whether VMREAD/VMWRITE may touch it.
 * Every supported encoding appears in the table once; `is_high_half` marks the
 * second (high-32) encoding of a 64-bit field.
 */
typedef struct NHV_FIELD_DESC {
    uint32_t encoding;
    uint8_t  width;        /* NHV_WIDTH_* */
    uint8_t  access;       /* NHV_ACCESS_* */
    uint8_t  is_high_half; /* 1 when this is the high-32 encoding */
} NHV_FIELD_DESC;

/*
 * Look up a field descriptor by encoding.
 * Returns non-NULL when the encoding is a supported VMCS field.
 */
const NHV_FIELD_DESC* nhv_field_lookup(uint32_t encoding);

/*
 * The number of supported encodings (including high-half encodings).
 */
uint32_t nhv_field_count(void);

/* Selected encodings (the subset this module currently models). */

/* 16-bit control fields */
#define NHV_VPID                       NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_CONTROL, 0x00)

/* 16-bit guest-state fields */
#define NHV_GUEST_ES_SELECTOR          NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_GUEST, 0x00)
#define NHV_GUEST_CS_SELECTOR          NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_GUEST, 0x02)
#define NHV_GUEST_SS_SELECTOR          NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_GUEST, 0x04)
#define NHV_GUEST_DS_SELECTOR          NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_GUEST, 0x06)
#define NHV_GUEST_FS_SELECTOR          NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_GUEST, 0x08)
#define NHV_GUEST_GS_SELECTOR          NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_GUEST, 0x0A)
#define NHV_GUEST_LDTR_SELECTOR        NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_GUEST, 0x0C)
#define NHV_GUEST_TR_SELECTOR          NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_GUEST, 0x0E)

/* 16-bit host-state fields */
#define NHV_HOST_ES_SELECTOR           NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_HOST, 0x00)
#define NHV_HOST_CS_SELECTOR           NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_HOST, 0x02)
#define NHV_HOST_SS_SELECTOR           NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_HOST, 0x04)
#define NHV_HOST_DS_SELECTOR           NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_HOST, 0x06)
#define NHV_HOST_FS_SELECTOR           NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_HOST, 0x08)
#define NHV_HOST_GS_SELECTOR           NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_HOST, 0x0A)
#define NHV_HOST_TR_SELECTOR           NHV_FIELD_ENCODE(NHV_WIDTH_16, 0, NHV_TYPE_HOST, 0x0C)

/* 64-bit control fields */
#define NHV_IO_BITMAP_A                NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_CONTROL, 0x00)
#define NHV_IO_BITMAP_B                NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_CONTROL, 0x02)
#define NHV_MSR_BITMAP_ADDRESS         NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_CONTROL, 0x04)
#define NHV_VMEXIT_MSR_STORE_ADDRESS   NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_CONTROL, 0x06)
#define NHV_VMEXIT_MSR_LOAD_ADDRESS    NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_CONTROL, 0x08)
#define NHV_VMENTRY_MSR_LOAD_ADDRESS   NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_CONTROL, 0x0A)
#define NHV_TSC_OFFSET                 NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_CONTROL, 0x10)
#define NHV_EPT_POINTER                NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_CONTROL, 0x1A)

/* 64-bit guest-state fields */
#define NHV_GUEST_VMCS_LINK_POINTER    NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_GUEST, 0x00)
#define NHV_GUEST_IA32_DEBUGCTL        NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_GUEST, 0x02)
#define NHV_GUEST_IA32_EFER            NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_GUEST, 0x06)

/* 64-bit host-state fields */
#define NHV_HOST_IA32_EFER             NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_HOST, 0x02)

/* 64-bit read-only (VM-exit info) fields */
#define NHV_GUEST_PHYSICAL_ADDRESS     NHV_FIELD_ENCODE(NHV_WIDTH_64, 0, NHV_TYPE_RO, 0x00)

/* 32-bit control fields */
#define NHV_PIN_CONTROLS               NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x00)
#define NHV_PRIMARY_CONTROLS           NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x02)
#define NHV_EXCEPTION_BITMAP           NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x04)
#define NHV_PF_ERROR_CODE_MASK         NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x06)
#define NHV_PF_ERROR_CODE_MATCH        NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x08)
#define NHV_CR3_TARGET_COUNT           NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x0A)
#define NHV_EXIT_CONTROLS              NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x0C)
#define NHV_ENTRY_CONTROLS             NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x12)
#define NHV_ENTRY_INTR_INFO            NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x16)
#define NHV_ENTRY_EXCEPTION_ERROR      NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x18)
#define NHV_ENTRY_INSTRUCTION_LENGTH   NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x1A)
#define NHV_SECONDARY_CONTROLS         NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_CONTROL, 0x1E)

/* 32-bit read-only (VM-exit info) fields */
#define NHV_VM_INSTRUCTION_ERROR       NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_RO, 0x00)
#define NHV_EXIT_REASON                NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_RO, 0x02)
#define NHV_EXIT_INTERRUPTION_INFO     NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_RO, 0x04)
#define NHV_EXIT_INTERRUPTION_ERROR    NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_RO, 0x06)
#define NHV_IDT_VECTORING_INFO         NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_RO, 0x08)
#define NHV_IDT_VECTORING_ERROR        NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_RO, 0x0A)
#define NHV_EXIT_INSTRUCTION_LENGTH    NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_RO, 0x0C)
#define NHV_EXIT_INSTRUCTION_INFO      NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_RO, 0x0E)

/* 32-bit guest-state fields */
#define NHV_GUEST_ES_LIMIT             NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x00)
#define NHV_GUEST_CS_LIMIT             NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x02)
#define NHV_GUEST_SS_LIMIT             NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x04)
#define NHV_GUEST_DS_LIMIT             NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x06)
#define NHV_GUEST_FS_LIMIT             NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x08)
#define NHV_GUEST_GS_LIMIT             NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x0A)
#define NHV_GUEST_LDTR_LIMIT           NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x0C)
#define NHV_GUEST_TR_LIMIT             NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x0E)
#define NHV_GUEST_GDTR_LIMIT           NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x10)
#define NHV_GUEST_IDTR_LIMIT           NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x12)
#define NHV_GUEST_ES_ACCESS            NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x14)
#define NHV_GUEST_CS_ACCESS            NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x16)
#define NHV_GUEST_SS_ACCESS            NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x18)
#define NHV_GUEST_DS_ACCESS            NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x1A)
#define NHV_GUEST_FS_ACCESS            NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x1C)
#define NHV_GUEST_GS_ACCESS            NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x1E)
#define NHV_GUEST_LDTR_ACCESS          NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x20)
#define NHV_GUEST_TR_ACCESS            NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x22)
#define NHV_GUEST_INTERRUPTIBILITY     NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x24)
#define NHV_GUEST_ACTIVITY_STATE       NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x26)
#define NHV_GUEST_SYSENTER_CS          NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_GUEST, 0x2A)

/* 32-bit host-state fields */
#define NHV_HOST_SYSENTER_CS           NHV_FIELD_ENCODE(NHV_WIDTH_32, 0, NHV_TYPE_HOST, 0x00)

/* natural-width read-only (VM-exit info) fields */
#define NHV_EXIT_QUALIFICATION         NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_RO, 0x00)
#define NHV_IO_RCX                     NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_RO, 0x02)
#define NHV_IO_RSI                     NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_RO, 0x04)
#define NHV_IO_RDI                     NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_RO, 0x06)
#define NHV_IO_RIP                     NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_RO, 0x08)
#define NHV_GUEST_LINEAR_ADDRESS       NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_RO, 0x0A)

/* natural-width guest-state fields */
#define NHV_GUEST_ES_BASE              NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x00)
#define NHV_GUEST_CS_BASE              NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x02)
#define NHV_GUEST_SS_BASE              NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x04)
#define NHV_GUEST_DS_BASE              NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x06)
#define NHV_GUEST_FS_BASE              NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x08)
#define NHV_GUEST_GS_BASE              NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x0A)
#define NHV_GUEST_LDTR_BASE            NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x0C)
#define NHV_GUEST_TR_BASE              NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x0E)
#define NHV_GUEST_GDTR_BASE            NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x10)
#define NHV_GUEST_IDTR_BASE            NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x12)
#define NHV_GUEST_DR7                  NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x14)
#define NHV_GUEST_RSP                  NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x16)
#define NHV_GUEST_RIP                  NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x18)
#define NHV_GUEST_RFLAGS               NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x1A)
#define NHV_GUEST_PENDING_DBG_EXC      NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x1C)
#define NHV_GUEST_SYSENTER_ESP         NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x1E)
#define NHV_GUEST_SYSENTER_EIP         NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x20)
#define NHV_GUEST_CR0                  NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x24)
#define NHV_GUEST_CR3                  NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x26)
#define NHV_GUEST_CR4                  NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_GUEST, 0x28)

/* natural-width host-state fields */
#define NHV_HOST_CR0                   NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x00)
#define NHV_HOST_CR3                   NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x02)
#define NHV_HOST_CR4                   NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x04)
#define NHV_HOST_FS_BASE               NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x06)
#define NHV_HOST_GS_BASE               NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x08)
#define NHV_HOST_TR_BASE               NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x0A)
#define NHV_HOST_GDTR_BASE             NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x0C)
#define NHV_HOST_IDTR_BASE             NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x0E)
#define NHV_HOST_SYSENTER_ESP          NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x10)
#define NHV_HOST_SYSENTER_EIP          NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x12)
#define NHV_HOST_RSP                   NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x14)
#define NHV_HOST_RIP                   NHV_FIELD_ENCODE(NHV_WIDTH_NAT, 0, NHV_TYPE_HOST, 0x16)

#endif /* NHV_VMCS_H */
